## 벡터와 행렬 연산

### 벡터와 행렬과 텐서

- 벡터는 크기와 방향을 가진 양.
- 숫자가 나열된 형상이며 파이썬에서는 1차원 배열 또는 리스트로 표현.
- 행렬은 행과 열을 가지는 2차원 형상을 가진 구조. 파이썬에서는 2차원 배열로 표현.
- 가로줄을 행(row)라고 하며, 세로줄을 열(column)이라고 함.
- 3차원부터는 주로 텐서라고 부름. 텐서는 파이썬에서는 3차원 이상의 배열로 표현.

### 텐서

- 인공 신경망은 복잡한 모델 내의 연산을 주로 행렬 연산을 통해 해결 가능.

#### 0차원 텐서(스칼라)

- 스칼라는 하나의 실수값으로 이루어진 데이터. 이를 0차원 텐서라고 함.

In [2]:
import numpy as np

d = np.array(5)

print('텐서의 차원 : ', d.ndim)
print('텐서의 크기(shape) : ', d.shape)

텐서의 차원 :  0
텐서의 크기(shape) :  ()


- Numpy의 ndim을 출력했을 때 나오는 값에 주목.
- ndim을 출력했을 때 나오는 값을 축(axis)의 개수 또는 텐서의 차원이라고 부름.

#### 1차원 텐서(벡터)

- 숫자를 배열한 것을 벡터라고 함. 벡터는 1차원 텐서임.

In [3]:
d = np.array([1, 2, 3, 4])
print('텐서의 차원 : ', d.ndim)
print('텐서의 크기(shape) : ', d.shape)

텐서의 차원 :  1
텐서의 크기(shape) :  (4,)


- 벡터에서의 차원은 하나의 축에 놓인 원소의 개수를 의미하는 것이고, 텐서에서의 차원은 축의 개수를 의미.

#### 2차원 텐서(행렬)

- 행과 열이 존재하는 벡터의 배열. 즉 행렬(matrix)을 2차원 텐서라고 함.

In [4]:
# 3행 4열의 행렬

d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('텐서의 차원 : ', d.ndim)
print('텐서의 크기(shape) : ', d.shape)

텐서의 차원 :  2
텐서의 크기(shape) :  (3, 4)


- 텐서의 크기란, 각 축을 따라서 얼마나 많은 차원이 있는지를 나타낸 값.
- 위의 경우 3개의 커다란 데이터가 있는데 그 각각의 커다란 데이터는 작은 데이터 4개로 이루어져있다고 생각할 수 있음.

#### 3차원 텐서(다차원 배열)

- 행렬 또는 2차원 텐서를 단위로 한 번 더 배열하면 3차원 텐서라고 부름.

In [5]:
d = np.array([
    [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [10, 11, 12, 13, 14]],
    [[15, 16, 17, 18, 19], [19, 20, 21, 22, 23], [23, 24, 25, 26, 27]]
])

print('텐서의 차원 : ', d.ndim)
print('텐서의 크기(shape) : ', d.shape)

텐서의 차원 :  3
텐서의 크기(shape) :  (2, 3, 5)


- 자연어 처리에서 자주 보게 되는 것이 3차원 텐서임.
- 3차원 텐서는 시퀀스 데이터를 표현할 때 자주 사용됨.
- 시퀀스 데이터는 주로 단어의 시퀀스를 의미하며, 시퀀스는 주로 문장이나 문서, 뉴스 기사 등의 텍스트가 될 수 있음.
- 이 경우 3차원 텐서가 됨.

### 벡터와 행렬의 덧셈과 뺄셈

In [6]:
A = np.array([8, 4, 5])
B = np.array([1, 2, 3])

print('두 벡터의 합 : ', A+B)
print('두 벡터의 차 : ', A-B)

두 벡터의 합 :  [9 6 8]
두 벡터의 차 :  [7 2 2]


In [7]:
A = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
B = np.array([[5, 6, 7, 8], [1, 2, 3, 4]])

print('두 행렬의 합 : ')
print(A + B)
print('두 행렬의 차 : ')
print(A - B)

두 행렬의 합 : 
[[15 26 37 48]
 [51 62 73 84]]
두 행렬의 차 : 
[[ 5 14 23 32]
 [49 58 67 76]]


### 벡터의 내적과 행렬의 곱셈

In [8]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

print('두 벡터의 내적 : ', np.dot(A, B))

두 벡터의 내적 :  32


In [9]:
A = np.array([[1, 3], [2, 4]])
B = np.array([[5, 7], [6, 8]])

print('두 행렬의 행렬곱 : ')
print(np.matmul(A, B))

두 행렬의 행렬곱 : 
[[23 31]
 [34 46]]
