In [1]:
import numpy as np
import torch

### View (Reshape)

- Reshape : 모양을 다시 만들어준다.

In [2]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
             
              [[6, 7, 8],
               [9, 10, 11]]])

ft = torch.FloatTensor(t)
print(ft.shape) # 2 X 2 X 3 = 12

torch.Size([2, 2, 3])


In [7]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape) # (2 X 2, 3) = (4, 3), 4 X 3 = 12

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [8]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape) # (2 X 2, 1, 3) = (4, 1, 3), 4 X 1 X 3 = 12

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze

In [9]:
# 원하는 dimension, 또는 전체에서 하나만 남아있는 경우에 없애주는 역할
# dimension의 element 개수가 1인 경우에 그 dimension을 없애줌

ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [10]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze

In [11]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [12]:
print(ft.unsqueeze(0)) # dim = 0과 같음
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [13]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [14]:
print(ft.unsqueeze(1)) # dim = 1
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [15]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Type Casting

In [16]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [18]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [19]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [20]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenate

- 이어붙이기

In [21]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [22]:
print(torch.cat([x, y], dim = 0)) # 4 X 2
print(torch.cat([x, y], dim = 1)) # 2 X 4

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

- Concatenate를 편리하게 해주는 함수

In [23]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [24]:
print(torch.stack([x, y, z])) # 3 X 2
print(torch.stack([x, y, z], dim = 1)) # 2 X 3

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [25]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros

In [26]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [28]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [29]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [30]:
print(x.mul(2.))
print(x)
print(x.mul_(2.)) # 결과값이 x로 들어감
print(x) 

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
