## Load Data

### Slicing 1D Array

In [1]:
nums = [0, 1, 2, 3, 4]
print(nums)

[0, 1, 2, 3, 4]


- index 2에서 4 전까지 가져와라.(앞 포함, 뒤 비포함)

In [2]:
print(nums[2:4])

[2, 3]


- index 2부터 다 가져와라.

In [3]:
print(nums[2:])

[2, 3, 4]


- index 2 전까지 가져와라. (뒤는 비포함)

In [4]:
print(nums[:2])

[0, 1]


- 전부 가져와라.

In [5]:
print(nums[:])

[0, 1, 2, 3, 4]


- 마지막 index 전까지 가져와라.(뒤는 비포함)

In [6]:
print(nums[:-1])

[0, 1, 2, 3]


- assign도 가능

In [7]:
nums[2:4] = [8, 9]
print(nums)

[0, 1, 8, 9, 4]


### Slicing 2D Array

In [8]:
import numpy as np

In [9]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [11]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
b[:, 1]

array([ 2,  6, 10])

In [14]:
b[-1]

array([ 9, 10, 11, 12])

In [16]:
b[-1, :]

array([ 9, 10, 11, 12])

In [17]:
b[-1, ...]

array([ 9, 10, 11, 12])

In [18]:
b[0:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Loading Data From `.csv` file

In [19]:
xy = np.loadtxt('data-01-test-score.csv', delimiter = ',', dtype = np.float32)

In [20]:
X_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [22]:
print(X_data.shape)
print(len(X_data))
print(X_data[:5])

(25, 3)
25
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]


In [23]:
print(y_data.shape)
print(len(y_data))
print(y_data[:5])

(25, 1)
25
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


### Import

In [25]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [27]:
torch.manual_seed(1)

### Low-level Implementation

In [28]:
# 데이터
X_train = torch.FloatTensor(X_data)
y_train = torch.FloatTensor(y_data)

# 모델 초기화
W = torch.zeros((3, 1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr = 1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    hypothesis = X_train.matmul(W) + b
    
    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 100번마다 로그 출력
    print('Epoch {:4d}/{} Cost : {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 Cost : 26811.960938
Epoch    1/20 Cost : 9920.530273
Epoch    2/20 Cost : 3675.299072
Epoch    3/20 Cost : 1366.260620
Epoch    4/20 Cost : 512.542480
Epoch    5/20 Cost : 196.896606
Epoch    6/20 Cost : 80.190994
Epoch    7/20 Cost : 37.038696
Epoch    8/20 Cost : 21.081335
Epoch    9/20 Cost : 15.178759
Epoch   10/20 Cost : 12.993677
Epoch   11/20 Cost : 12.183028
Epoch   12/20 Cost : 11.880536
Epoch   13/20 Cost : 11.765964
Epoch   14/20 Cost : 11.720855
Epoch   15/20 Cost : 11.701437
Epoch   16/20 Cost : 11.691509
Epoch   17/20 Cost : 11.685122
Epoch   18/20 Cost : 11.680006
Epoch   19/20 Cost : 11.675371
Epoch   20/20 Cost : 11.670942


### High-level Implementation with `nn.Module`

In [29]:
class MultivatiateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)
        
    def forward(self, x):
        return self.linear(x)

In [37]:
# 데이터
X_train = torch.FloatTensor(X_data)
y_train = torch.FloatTensor(y_data)

# 모델 초기화
model = MultivatiateLinearRegressionModel()

# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr = 1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    pred = model(X_train)
    
    # cost 계산
    cost = F.mse_loss(pred, y_train)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 20번마다 로그 출력
    print('Epoch {:4d}/{} Cost : {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 Cost : 27651.355469
Epoch    1/20 Cost : 10232.179688
Epoch    2/20 Cost : 3791.824707
Epoch    3/20 Cost : 1410.643921
Epoch    4/20 Cost : 530.250732
Epoch    5/20 Cost : 204.741638
Epoch    6/20 Cost : 84.387695
Epoch    7/20 Cost : 39.885597
Epoch    8/20 Cost : 23.428125
Epoch    9/20 Cost : 17.339361
Epoch   10/20 Cost : 15.084238
Epoch   11/20 Cost : 14.246533
Epoch   12/20 Cost : 13.932904
Epoch   13/20 Cost : 13.813032
Epoch   14/20 Cost : 13.764787
Epoch   15/20 Cost : 13.743059
Epoch   16/20 Cost : 13.731115
Epoch   17/20 Cost : 13.722813
Epoch   18/20 Cost : 13.715851
Epoch   19/20 Cost : 13.709385
Epoch   20/20 Cost : 13.703098
